USE Book_Management;
CREATE TABLE Book(
Id VARCHAR(45) PRIMARY KEY,
TenSach VARCHAR(45),
TacGia VARCHAR(45),
TheLoai VARCHAR(45),
GiaTien INT
);

CREATE TABLE Customers(
Id INT PRIMARY KEY,
Ten VARCHAR(45),
DiaChi VARCHAR(255),
SoDT VARCHAR(45),
Id_SachMua VARCHAR(45),
FOREIGN KEY (Id_SachMua) REFERENCES Book(Id)
);