USE QuanLyBanHang;
CREATE TABLE Customers(
cID INT PRIMARY KEY,
cName VARCHAR(45),
cAge INT
);

CREATE TABLE Orders(
oID INT PRIMARY KEY,
cID INT,
oDate DATE,
oTotalPrice INT,
FOREIGN KEY (cID) REFERENCES Customers(cID)
);

CREATE TABLE Products(
pID INT PRIMARY KEY,
pName VARCHAR(45),
pPrice INT 
);

CREATE TABLE OrderDetail(
PRIMARY KEY (oID, pID),
FOREIGN KEY (oID) REFERENCES Orders(oID),
FOREIGN KEY (pID) REFERENCES Products(pID),
odQTY INT
);