CREATE DATABASE MYBANKING;

USE MYBANKING;

CREATE TABLE CUSTOMERS
(
	ID_CUSTOMER INT AUTO_INCREMENT PRIMARY KEY,
    FULLNAME_CUSTOMER VARCHAR(50),
    PHONE_NUMBER VARCHAR(15),
    EMAIL VARCHAR(50),
    ADDRESS VARCHAR(50),
    BALANCE DECIMAL
);

CREATE TABLE DEPOSIT
(
	ID_DEPOSIT INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT_DEPOSIT DECIMAL,
    DATE_DEPOSIT DATETIME,
    ID_CUSTOMER INT REFERENCES CUSTOMERS(ID_CUSTOMER)
);

CREATE TABLE WITHDRAW
(
	ID_WITHDRAW INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT_WITHDRAW DECIMAL,
    DATE_WITHDRAW DATETIME,
    ID_CUSTOMER INT REFERENCES CUSTOMERS(ID_CUSTOMER)
);

CREATE TABLE TRANSFER
(
	ID_TRANSFER INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT_TRANSFER DECIMAL,
    DATE_TRANSFER DATETIME,
    ID_SENDER INT REFERENCES CUSTOMER(ID_CUSTOMER),
    ID_RECIPIENT INT REFERENCES CUSTOMER(ID_CUSTOMER)
);